FROM node:10.16.3-alpine

RUN apk update && apk upgrade
RUN npm install -g yarn

ARG FRONTEND_DIR=/opt/stop-covid-frontend-hybrid

RUN mkdir $FRONTEND_DIR

COPY package.json $FRONTEND_DIR
COPY yarn.lock $FRONTEND_DIR

WORKDIR $FRONTEND_DIR

RUN yarn

COPY . $FRONTEND_DIR

############ ENV
ARG BASE_URL
ENV BASE_URL $BASE_URL

ARG API_HOST
ENV API_HOST $API_HOST

ARG AUTHORIZATION_TOKEN
ENV AUTHORIZATION_TOKEN $AUTHORIZATION_TOKEN

ARG PEER_SERVER_HOST
ENV PEER_SERVER_HOST $PEER_SERVER_HOST

ARG PEER_SERVER_PORT
ENV PEER_SERVER_PORT $PEER_SERVER_PORT

ARG PEER_SERVER_KEY
ENV PEER_SERVER_KEY $PEER_SERVER_KEY

RUN yarn build

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

CMD [ "yarn", "start" ]
